title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          type: markdown
          listable: hidden
          display: Description
      -
        handle: gallery
        field:
          mode: grid
          container: assets
          restrict: false
          allow_uploads: true
          max_files: 3
          display: 'Gallery Images'
          type: assets
          icon: assets
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: price
        field:
          read_only: false
          type: money
          listable: hidden
          display: Price
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
